---
title: "Chicken Weights Analysis"
author: "Kholoud Sindi"
date: "04/09/2020"
output:
  html_document:
    toc: true
    toc_float: true

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE )
library(tidyverse)
library(DT)
library(knitr)
```



# Discriptive data

```{r Summary, echo = FALSE}
chickTable <- chickwts %>% 
  group_by(feed) %>% 
  summarise(n = n(), 
            avarage = mean(weight),
            SD = sd(weight))
datatable(chickTable)
```

# Plots

```{r BoxPlot, echo=FALSE}
library(tidyverse)
ggplot(chickwts, aes(x = feed, y = weight))  + 
  geom_boxplot()
```

```{r Dots, echo=FALSE}
ggplot(chickwts, aes(x = feed, y = weight))  + 
   geom_jitter() +
  stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), col = "red")

```


# Inferential Statistics

The one-way ANOVA summary:

```{r Anova1, include=FALSE, results='hide'}
chickwts_lm <- lm(weight ~ feed, data = chickwts)
chickwts_lm
```

```{r Anova, echo=FALSE}
xx <- anova(chickwts_lm)
kable(xx)
```


Tukey’s Post-hoc test:


```{r test, echo=FALSE}

chickwts.av <- aov(weight ~ feed, data = chickwts)
tukeyTest <- TukeyHSD(chickwts.av)

datatable(tukeyTest$feed)
```


